### ISSUE TITLE
Inverted text colour in TV Channels

### ISSUE THREAD

**Issue by Mo1967** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#16]
Add-on Version: AZ2:R v1.0.20
Kodi Version: Nexus 20.5
Operating System: Android

Setting with transparency value 100% working fine for Movies, TV, Shows and TV Guide, but I've trouble  to see in TV Channels the program titles (screenshots below). Thanks a lot for this great skin

![063024164142](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/assets/157020721/f569ee66-8479-400e-80a7-cded555e739e)

![063024164308](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/assets/157020721/4e5977e5-61e7-422f-b810-8b70d7d5ebb1)
  
![063024164414](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/assets/157020721/ace3e6dc-2b67-4e88-83a9-cf48a8515bff)

![063024164224](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/assets/157020721/7ea1a93c-3570-4347-bf09-e4d7982ae68d)

**Comment by DenDyGH** [comment]
Hi, thanks for the report and sorry for the late reply. It should be fixed now.

**Comment by DenDyGH** [comment]
@Mo1967 done. Test version -> [Nexus](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/nexus.zip) / [Omega](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip)
