### ISSUE TITLE
[Request/Option] Two in one (Read Description)

### ISSUE THREAD

**Issue by Nuklear92** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#17]
Alright, so I have two things to kindly ask. Hopefully they both can be easy adds.

First, for the Flix homescreen there seems to be this "Match with %" which I've looked everywhere within the skin settings for an option to turn it off, as it always shows a completely different rating score compared to what you get from the individual ratings with OMdb or MDblist which I personally use. Also, with TV shows it makes some of the text fall off the edge, specifically as you know when you're scrolling through titles after the "Returning/Cancelled,etc" text it shows the date of the last episode that was aired from that show. Sometimes the numbers cuts off the available displayed text line. This is only seen when you have widgets in the homepage.

![image](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/assets/76958541/3f01cded-575b-46af-9cda-e624ba881eab)

**Example of text cutting off due to the Match %** see the red arrow.

![image](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/assets/76958541/ef180913-b5a5-4829-8da2-d5288d35acfa)

Okay, now this is the second request of course if it's possible and not difficult to remake. And that is, the **in progress icon** as you will see in the screenshot below, you can barely tell it's there and looks out place with the landscape thumb.

![image](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/assets/76958541/34d73e39-17bd-4468-bad4-8184c11c6f54)

This is an example of how it looks in Arctic Fuse

![image](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/assets/76958541/385ebfce-ce4e-4a7e-806c-cba8ae6e41e9)

Lastly, hopefully you can eventually upgrade the current home layout **"Flix View|Multiple widgets"** and bring those new Flix view style you added for Flix Posters2 and Flix Landscape that looks nicer and cleaner. 

You can tell the difference mostly with the new Flix Landscape view, compared to the homepage Landscape view.

![image](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/assets/76958541/85c86b29-2f93-4945-ba08-7d3f0800c79b)
![image](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/assets/76958541/654d9e8f-f28c-4a6c-b8d0-df8b80f5df3e)

**Comment by DenDyGH** [comment]
Second one is definitly a bug, but can't reproduce it. Is that Library or an addon?

**Comment by Nuklear92** [comment]
> Second one is definitly a bug, but can't reproduce it. Is that Library or an addon?

Add-on, could this be possibly related to that addon in specific. Because, I checked within the TMDB helper addon and the progress icon looks similar to the one in Arctic Fuse. 🤷‍♂️

**Comment by DenDyGH** [comment]
Well, if this particular addon works in Fuse, then it should work also in AZ2. What is this addon?

**Comment by Nuklear92** [comment]
> Well, if this particular addon works in Fuse, then it should work also in AZ2. What is this addon?

FEN and FENLight, either way if this issue is related or fixable by the dev of the add-on you can skip it and perhaps just do the optional option of turning on/off the **Match %** when using homepage widgets. 

Or perhaps if you had any plans of upgrading the current Flix home layout to be similar to the newer Flix Landscape and Flix Poster 2 you added. Also, when you place widgets there are two "Aspects" you can choose for Landscape "Big or Small". The small one I tried it, but it looks a bit off since it displays the title and episode name below the artwork within a black bar and doesn't look as clean as when you use the Flix Landscape within add-ons. 

Just these subtle changes sometimes makes using the views within add-ons more enjoyable than using widgets in the homepage.

**Comment by Nuklear92** [comment]
> Should be fixed now, also added option for disabling match info. It's in `Skin Settings > Library > Hide match info in widgets`.
> 
> You can download zip and test it out: [Omega](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip)
> 
> 
> 
> I have no plans to make any changes to the widgets at the moment, but I may do so in the near future.

I'll, check it out!

**Comment by Nuklear92** [comment]
> Should be fixed now, also added option for disabling match info. It's in `Skin Settings > Library > Hide match info in widgets`.
> 
> You can download zip and test it out: [Omega](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip)
> 
> 
> 
> I have no plans to make any changes to the widgets at the moment, but I may do so in the near future.

Progress icon is now showing correctly, and also the option for removing the Match %. Thanks for the fix and added option! 😃👍

![image](https://github.com/user-attachments/assets/ebc0a29f-6c2e-40c0-b93f-10fcf4d2bdc6)

**Comment by Nuklear92** [comment]
@DenDyGH I didn't wanted to open another issue just for this, since this issue still open. Here's another small issue I've noticed, whenever there's any light background text seems to get lost in it, as you'll see in the screenshot below. The same issue is present when scrolling through the homepage widgets, depending if the title you're scrolling has a light or whiteish background artwork you can barely read the text plot, among other meta info. I don't know if this can be fixed by applying text outlines since the current text doesn't seem to have. 

![image](https://github.com/user-attachments/assets/e6ef67b8-793b-4a92-afca-83b64ffabbe9)

That's an example of how the text gets lost whenever there's a light background. Hopefully this fix can be added to the other bunch of improvements you did with my original issue post, before pushing the update to everyone. 👍

**Comment by DenDyGH** [comment]
Done, should be ok now.

**Comment by Nuklear92** [comment]
> Done, should be ok now.

Appreciate the quick fix 🙏. I'll be sure to report any future bugs/issues I discover that could potentially enhance the way the skin works or looks.

For now, you can safely close this issue as all of them requests were successfully resolved. 🙂
