### ISSUE TITLE
Double icon of red Rotten Tomatoes in the plot of movies

### ISSUE THREAD

**Issue by Mo1967** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#19]
**Context**

Please provide any relevant information about your setup
    Add-on Version: AZ2:R v1.0.21
    Kodi Version: 20.5 Nexus
    Operating System: Android  

**Expected Behavior**
Displayed rating Rotten Tomatoes shows one icon (tomato) in the plot

**Current Behavior**
Displayed two red tomatoes (fresh status) in the plot and wrong Rotten status 
![rtfresh](https://github.com/user-attachments/assets/f3cf80de-b7aa-433a-b1b6-5146474bb0a7) ![rtfresh](https://github.com/user-attachments/assets/b6026263-82ff-4fa7-868a-ad83fd695c57)
![rtrotten](https://github.com/user-attachments/assets/6e35b3a9-a74a-483c-b328-2c14a351fcc2)

**Steps to Reproduce**
Setting 'Simple on-screen indo (hide poster and plot)' deactivated.
Choose displayed rating Rotten Tomatoes in the settings and starting movie and open player.

**Additional Information**
Example
![IMG_4795](https://github.com/user-attachments/assets/a57770da-a158-4fb8-a74a-cbcd3b7fdab2)

**Comment by DenDyGH** [comment]
Can you please check it out? [Nexus](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/nexus.zip) or [Omega](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip)
