### ISSUE TITLE
Highlight color

### ISSUE THREAD

**Issue by Arthur1967** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#2]
![image](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/assets/69996032/fc9556dc-8576-47f1-b840-f9405cf69c33) is there a way to change this from white thank you for the skin. It works well.

**Comment by DenDyGH** [comment]
Yes, it will be possible in the next version. It's not yet released in repository because it still needs some adjustments.
If you want, you can check it out by downloading zip directly from github https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip

**Comment by Arthur1967** [comment]
OK, thanks I love what you've done. I will be using it. I just disable the movie database helper and it works faster. Thank you.
