### ISSUE TITLE
Feature Request: Displayed ratings in the views

### ISSUE THREAD

**Issue by Mo1967** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#20]
### Context

Please provide any relevant information about your setup

* Add-on Version: AZ2:R v1.0.21
* Kodi Version: 20.5
* Operating System: Android

------

### Expected Behavior

Displayed ratings in all views (with space) like in Information or Flix views;, Poster and Landscape Showcase;  Poster

------

### Current Behavior

What is the current behavior?
Complete ratings not in views like Media Info and Media Info 2,, also not in the plot of player.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Select movie
2. Test all views and plot in the player to point out your *Choose displayed ratings* in the settings.
3. 
------

### Additional Information

Please provide any additional information that may be helpful.
Screenshots
![072224093956](https://github.com/user-attachments/assets/3867c95c-a281-46ea-9b75-0c01ab02b11a)
![072224094153](https://github.com/user-attachments/assets/1ba6c7e0-9673-497b-a5c2-c4666b21e61b)

------

**Comment by DenDyGH** [comment]
This is intentional because there is not enough space in these views to show everything. I can't predict which ratings a user will have enabled.
