### ISSUE TITLE
🚀Feature Request: Bookmarks button in the player

### ISSUE THREAD

**Issue by Mo1967** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#22]
### Relevant information about setup

Add-on Version: AZ2:R v1.0.22
Kodi Version: Nexus 20.5
Operating System: Android

------

### What Problem Does This Solve? 

Too much steps to set bookmarks in AZ2:R :
1. Play video file
2. Open Player
3. Navigate to Settings button for Options
4. Navigate to Bookmarks
5. CREATE BOOKMARK

------

### Suggest a Solution

Set Bookmarks with AZ2:R skin directly in the player like in Estuary skin (below pic)
Suggestion: additionally AZ2:R setting  in section Video/Music  `Hide bookmarks button` 

![Screenshot 2024-08-25 043054](https://github.com/user-attachments/assets/d2eef1f9-37ab-4ecd-87fe-0065dc5890fb)

------

**Comment by DenDyGH** [comment]
Done. Button is enabled by default and can be disabled in settings.

**Comment by DenDyGH** [comment]
In `userdata\Database\MyVideos131.db`, table `bookmark`.
