### ISSUE TITLE
Skin cannot be enabled on Kodi 21.1

### ISSUE THREAD

**Issue by SirChomby** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#23]
I recently updated to Kodi 21.1 and can no longer enable the Arctic Zephyr 2 Resurrection skin (version 1.0.22)

It throws the error message "This add-on is not compatible with this version of Kodi".

**Comment by DenDyGH** [comment]
Are you installing the correct omega skin version? It works fine for me.

**Comment by SirChomby** [comment]
Oh thank you! That worked. I manually installed the omega version from GitHub after uninstalling the Kodi Repo version (and keeping add-on data).
