### ISSUE TITLE
Modern - how to move widgets down

### ISSUE THREAD

**Issue by derrgoo** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#25]
![image](https://github.com/user-attachments/assets/e6eb9279-1cbe-477a-977b-78d38f017162)

As you can see some descriptions of series or movies get caught off because the widgets bar is too high. Is there a way to move down the widget bar just a bit so descriptions don't get caught off in modern view? Thank you

1.0.23
Kodi 21.1
Shield pro

**Comment by DenDyGH** [comment]
Weird but can't reproduce it. Did you change font or something?

**Comment by derrgoo** [comment]
I think that was what it was. Playing with the different font options. I changed back and seem to resolve the issue. 

Question: is it possible to hide menu like modern when using flix? Flix seems to stay at the left even when on the widgets.

**Comment by DenDyGH** [comment]
It should hide automatically, that's how it works.

**Comment by derrgoo** [comment]
Flix doesn't hide for me. Maybe I am not doing something right. It seems to only hide on modern. 

![image](https://github.com/user-attachments/assets/e4dda058-7272-4a00-aec0-be3bf46f24e6)

**Comment by DenDyGH** [comment]
Ahh yes, that's becasue you are using "icons only"/"text + icons" style.
I will probably add a new option to hide the menu..

**Comment by derrgoo** [comment]
Cool. You have done a great job keeping this alive.

**Comment by DenDyGH** [comment]
Option has been added. It's in Skin Settings > Home > just below "Menu style" option.
If you want, you can install test version and check it out [Nexus](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/nexus.zip) / [Omega](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip)

**Comment by derrgoo** [comment]
Works awesome 👏 like it allot. Thanks

**Comment by derrgoo** [comment]
Last question :)) 

When you pull Trakt Progress Episodes it doesn't show CLEARART. 

For example:

![image](https://github.com/user-attachments/assets/ac11d9f2-f709-4414-ad45-62c592ef918b)

Now all other sections show it even trakt watchlist. 

For example:

![image](https://github.com/user-attachments/assets/2751cc09-5db7-422d-9828-aa7ce948206f)

I am using umbrella and I know his takes are in the add on because they will pull in horizon 2. I am thinking that they are missed in the skin part for this progress episodes. Is it possible to add these? 🙏

**Comment by DenDyGH** [comment]
Well, it's more on the umberlla side. I can't do anything about it. AH2 works kinda different and it use tmdb helper as fallback.

**Comment by DenDyGH** [comment]
You're confusing clearart with clearlogo.
In the screenshots you showed, the skin shows clearlogo, not clearart and mentioned addon does not provide it.

**Comment by derrgoo** [comment]
Yes clear logo. Sorry for the confusion. So is this the skin or add on?

**Comment by DenDyGH** [comment]
It's addon. Weird but it doesn't show clearlogo for me even in modern.
If you don't believe you can enable "debug: show arts path" in skin settings, then go directly to addon "My TV Shows -> Progress episodes" and you will see there's link to clearart but no clearlogo.
Then go to "My TV Shows -> Progress shows" and you will see there's clearlogo.

**Comment by derrgoo** [comment]
I definitely believe. I am not good at code. So confusing to me. lol I will do as you say and try.

**Comment by derrgoo** [comment]
Okay your right progress tv shows 👍
