### ISSUE TITLE
.... and Video extras ?

### ISSUE THREAD

**Issue by philamp** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#28]
according to https://kodi.wiki/view/Video_extras

thanks a lot if possible

(I guess I'm the number 1 functionnality requester right now... kind of sorry 😄 )

**Comment by DenDyGH** [comment]
Im not sure but should work :P [Omega](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip)

**Comment by philamp** [comment]
yeap working :)
