### ISSUE TITLE
Kodi keeps crashing when changing view type.

### ISSUE THREAD

**Issue by Hemicrusher** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#31]
Using Kodi 21 on GoogleTV

Kodi crashes to the GoogleTV home screen when changing view types with the new menu, which I guess was just added to AZ2R, This is happening in all addons... POV, Umbrella etc.  

This just started happening after yesterday's update.

[Kodi Log File](https://pastebin.com/rhpScrFZ)

Thanks!

**Comment by DenDyGH** [comment]
Yes, this is probably related to TMDB Helper Service Monitor.
I am waiting for a response from Jurial just to be sure, but it may take some time.
