### ISSUE TITLE
No codec icons in  video file view

### ISSUE THREAD

**Issue by frodo19** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#33]
There is no codec icons in  video file view.
Would be nice to enable those, as in other views

![02](https://github.com/user-attachments/assets/2919ccc6-4f95-4462-9d40-52d089e43737)

**Comment by DenDyGH** [comment]
Done. Can you check if everything is ok? [Omega](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip)

**Comment by frodo19** [comment]
> Done. Can you check if everything is ok? [Omega](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip)

Awesome!
Thank you 👍

**Comment by DenDyGH** [comment]
Hmm, I've never used it, but it looks like you are right.

**Comment by frodo19** [comment]
Thank you, you made awesome skin!

..can I request two thing more?

When playing musics, the fanart not changed, however the Artist slideshow enabled. This work in other skin.

Second, would be possible to made one favourites widget with vertical movement, same as the favourites browser?

Thank you

**Comment by DenDyGH** [comment]
Artist slideshow should be fixed now.

Im not sure what you mean by "favourites widget with vertical movement, same as the favourites browser"

**Comment by frodo19** [comment]
Thanks! 
I mean, same as in the estuary, or estuary modv2. One full page widget, with vertical movement.
I use the skin with multiple row widgets. 
But the favourites widget just one row. 
Thats why asked the full page.

**Comment by DenDyGH** [comment]
Sorry, no idea if that's even possible.

**Comment by frodo19** [comment]
Ok, thank you anyway.
