### ISSUE TITLE
During video playback, exiting information closes to main menu - FlixView

### ISSUE THREAD

**Issue by Infrared-prime** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#37]
As inferred in the title, whenever I click "information" during video playback, exiting the information page stops the video playback and opens main menu.

This only happens when the Home layout is set to FlixView, on any other choice of home layout the information page acts normally ie clicking information during video playback then exiting the information page just goes back to playing the video.

My setup is an android TV box and I am running Kodi 21.1

Thanks for your anticipated assistance, it's really appreciated.

**Comment by DenDyGH** [comment]
Thank you for reporting this. It should be fixed now.

**Comment by Infrared-prime** [comment]
Thank you for your speedy response, it's really appreciated.

I have tried to update to check the changes, unfortunately I can't, would
you advise I uninstall and reinstall

Thanks again, your skin is really awesome 👍🏾😎

Warm regards,

**Comment by DenDyGH** [comment]
Probably I will push new version to repository soon, but if you want you can download and install zip - [Omega](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip)

**Comment by Infrared-prime** [comment]
Seen,

Thank you very much.

**Comment by Infrared-prime** [comment]
I have installed the zip and tried it out, works perfectly 👍🏾

Issue is resolved.


Thank you very much for your assistance, really appreciate it.


Warm regards,
