### ISSUE TITLE
Display now playing video in background not working

### ISSUE THREAD

**Issue by Sorien** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#41]
Skin -> Background -> Display now playing video in background probably does nothing, It should replace background image with video overlay same as in Artic Zephyr skin

**Comment by DenDyGH** [comment]
Should be fixed now.

**Comment by DenDyGH** [comment]
Can you install from zip and try? [Omega](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip)
