### ISSUE TITLE
Ratings

### ISSUE THREAD

**Issue by tomschuetteprivat** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#42]
Hello,

I am trying to get ratings to work but they don't show up. I have entered my mdblist api key in tmdb helper and have ticked the boxes for IMDb and rotten tomatoes, for example.

However, none of the ratings except for tmdb ratings show up.

Does anyone have any advice?

**Comment by DenDyGH** [comment]
Can you try with OMDB Api key?

**Comment by tomschuetteprivat** [comment]
> Can you try with OMDB Api key?

This worked, thank you very much!
