### ISSUE TITLE
Grouped channels PVR

### ISSUE THREAD

**Issue by derrgoo** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#43]
Is it possible to add group channels as a widget. See example below

![image](https://github.com/user-attachments/assets/ed257c55-8549-4b2e-85a0-8b65ddc9ad90)

**Comment by DenDyGH** [comment]
Can you update skin from zip [Omega](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip) and try it?

You can set it here:
`Skin settings > Customise home menu > Widgets > Choose widget > Default Widgets > PVR > TV channel groups`
also set `Aspect` as `Small Square`.

**Comment by DenDyGH** [comment]
It is available in main branch and will be added to repository soon (in next skin version).
