### ISSUE TITLE
navigating through homepage menu widget should not stop actual playback

### ISSUE THREAD

**Issue by Sorien** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#44]
1. create homepage menu widget with some movie list.
2. play some movie 
3. return to homepage and go through that widget 
4. actual playback will be stopped

HomeLAyout Filx View - multiple widgets

**Comment by DenDyGH** [comment]
I hope it will be fine now. You can check by installing zip [Omega](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip)
