### ISSUE TITLE
Use TMDBHelper to crop clearlogo, then the ClearLogo visible in the menus

### ISSUE THREAD

**Issue by frodo19** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#45]
Hi, with the settings active [(commit) ](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/commit/c829212bfaa88a8cc45591ee7ae73f0481d63195#diff-34432f11137b9bc56e7aa1908e918ac1c82156da8e966d220b5960efd7f6f795R2204)"Use TMDBHelper to crop clearlogo", 
then the ClearLogo visible in the menus, and overlap the text.
![screenshot00001](https://github.com/user-attachments/assets/2ae3d82d-c1cb-4d75-8193-bc2a442c7063)
![screenshot00009](https://github.com/user-attachments/assets/b98b9263-7c3d-4a29-b2c4-efa3c23950e8)
![screenshot00011](https://github.com/user-attachments/assets/1a9e14bd-33e5-40cd-80cf-226b2736c9dc)

thanks
Merry Christmas

**Comment by DenDyGH** [comment]
Should be ok now

**Comment by frodo19** [comment]
Thank you
