### ISSUE TITLE
[Feature Request] option to replace playback duration with remaining time

### ISSUE THREAD

**Issue by nioncode** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#46]
Great skin!

It would be nice if one could replace the playback duration in the pause-screen with the remaining time (similar to the option to replace the `Show remaining time instead of end time` setting).

It could be shown as `00:31 | -00:07`, or maybe even add all three times in one line like `00:31 | -00:07 | Ends 22:34`

**Comment by DenDyGH** [comment]
Added in v1.0.33 :)

**Comment by nioncode** [comment]
That was fast, thank you! Just fyi, I was confused that this replaced the elapsed time instead of the duration. Maybe the setting name `Show time remaining instead of elapsed time` would be more appropriate. Functionality wise I'm fine with both :)
