### ISSUE TITLE
[Feature] Premiere & Season Finale labels on Episodes.

### ISSUE THREAD

**Issue by Nuklear92** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#6]
Greetings, I don't know if you're accepting any requests for features, bug fixes, improvements, etc. Been using your mod for a bit since I've always liked the simplicity and snappy feel of AZ in general. I was wondering since this skin also relies on TMDB helper, is it possible to add the same feature Jurial did with Arctic Fuse. I was the one who initially requested that feature on that skin as well and at first he thought it was kind of impossible but after a bit of research here and there. He ended up implementing the feature which is tied with TMDB helper. I believe if you dig around into Arctic Fuse code you might find how he implemented the feature, etc. 

Hence this not an obligatory feature, I just wanted to share that the feature has already been implemented with Arctic Fuse and I don't know if perhaps it's possible to copy it over to this skin since both rely on TMDB helper. 

If it's not possible, just close the issue on the fly. I'll be opening one or two more issues later on separately regarding some things I've noticed in the skin and perhaps one being an improvement. 👍

**Comment by DenDyGH** [comment]
Hi @Nuklear92, I have added this feature and it will be available in the next version.
The function must first be enabled in the settings.

> Skin Settings -> Library -> Premiere and finale indicators for series
