### ISSUE TITLE
Colored

### ISSUE THREAD

**Issue by Arthur1967** [DenDyGH/skin.arctic.zephyr.2.resurrection.mod#8]
![image](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/assets/69996032/c0057809-43a0-4ba7-b569-9d5191ef0fa1) this is more of a feature request. Is there anyway you can add colors? If not, I understand it just makes it easier to see. Thank you.

**Comment by DenDyGH** [comment]
Add colors to what?

**Comment by Arthur1967** [comment]
To the icons Trakt, the movie database,imdb just like shown in the picture I posted the ones currently are just white

**Comment by Arthur1967** [comment]
I find it just makes it easier to see. I used someone else's skin to demonstrate what I meant.

**Comment by Arthur1967** [comment]
![image](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/assets/69996032/d6b90022-8cfa-458e-86ef-83cf08664197) see how they're colored

**Comment by Arthur1967** [comment]
![image](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/assets/69996032/4ceb7351-966c-40a0-8255-3125f5d77e82) that's how they look now but if you could add color

**Comment by Arthur1967** [comment]
![image](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/assets/69996032/10dc622a-715c-457b-8a33-0784e8bbdcd4) that's how they would look I believe they're easier to see

**Comment by Arthur1967** [comment]
I'll just close it. I decided it would make it easier to see. Thank you.

**Comment by notoco** [comment]
But this option has been available for a long time:
![screenshot00044](https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/assets/36659110/164ccc29-61d7-47d3-8957-ba818ef4208a)

**Comment by Arthur1967** [comment]
My mistake thank you I like your skin because it works fast. Thank you very much. I will change it right now. Have a good day.
